spring:
  application:
    name: notification-service
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

server:
  port: 8083

rabbitmq:
  exchange:
    name: order.events.exchange
  queue:
    notification:
      name: notification.send.queue
  routing:
    key:
      notification: notification.send.routing.key
